workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.school_for_teach"
    scripts:
      - name: Установка зависимостей
        script: flutter pub get
      - name: Сборка релизного APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - alexeyofficialrddn@gmail.com